= CLI Options

You can configure the behavior of the Antora CLI and various playbook keys directly from your terminal using command line options.
This page lists these options, how to specify them, and how they are used.

== Precedence

The CLI options will override the value of corresponding keys defined in the playbook file as well as any environment variables.

== Global options

The options in the table below apply to the xref:index.adoc#usage[antora base call] and impact the behavior of the Antora CLI as a whole.

[cols="2,2,2,4"]
|===
|Option |Default |Values |Notes

|`-h`, `--help`
|_Not applicable_
|_Not applicable_
|Displays information about the command usage and its options and arguments.
See xref:index.adoc#help[Display Antora CLI help].

|[[require]]`-r`, `--require`
|Not set
|Node package name or filesystem path to a script
|Can specify multiple times.
See xref:playbook:asciidoc-extensions.adoc#preload-extensions[Preload Asciidoctor extensions].

|`--stacktrace`
|`false`
|<<boolean-value,Boolean>>
|Prints the stacktrace to the console if the application fails.
See <<ex-boolean-true>> and xref:ROOT:run-antora.adoc#error-stacktrace[Show error stacktrace].

|`-v`, `--version`
|_Not applicable_
|_Not applicable_
|Displays the current Antora version.
|===

[#generate-options]
== generate command options

The options in the table below apply only to the `generate` command.

[cols="2,2,2,4"]
|===
|Option |Default |Values |Notes

|[[attribute]]`--attribute`
|Not set
|AsciiDoc attribute in the form `<name>` or `<name=value>`
|Can specify multiple times.
See xref:playbook:asciidoc-attributes.adoc[] and <<ex-name-value-pair>>.

|[[cache-dir]]`--cache-dir`
|xref:playbook:runtime-cache-dir.adoc#default[Varies by operating system]
|Filesystem path
|See xref:playbook:runtime-cache-dir.adoc[] and
xref:playbook:environment-variables.adoc[ANTORA_CACHE_DIR variable].

|[[clean]]`--clean`
|`false`
|<<boolean-value,Boolean>>
|This option xref:playbook:output-dir.adoc#clean-warning[erases entire folders and their files]; use it with great care!
See xref:playbook:output-dir.adoc#clean-key[clean key], <<ex-multiple-options>> and <<ex-boolean-false>>.

|[[fetch]]`--fetch`
|`false`
|<<boolean-value,Boolean>>
|See xref:playbook:runtime-fetch.adoc[].

|`--generator`
|`@antora/site-generator-default`
|Node package name or filesystem path to a script
|Intended for advanced users comfortable with the inner workings of Antora.
Effectively substitutes Antora's entire pipeline with a user-defined function.

|[[git-credentials-path]]`--git-credentials-path`
|_$HOME/.git-credentials_ or +
_$XDG_CONFIG_HOME/git/credentials_
|Filesystem path
|See xref:playbook:private-repository-auth.adoc#custom-credential-path[git credentials file path] and xref:playbook:environment-variables.adoc[GIT_CREDENTIALS_PATH variable].

|[[google-key]]`--google-analytics-key`
|Not set
|Google Analytics API key
|See xref:playbook:site-keys.adoc#google-analytics-key[Google Analytics key] and xref:playbook:environment-variables.adoc[GOOGLE_ANALYTICS_KEY variable].

|`-h`, `--help`
|_Not applicable_
|_Not applicable_
|Displays information about the command usage and its options and arguments.
See xref:index.adoc#help[Display Antora CLI help].

|[[html-extension]]`--html-url-extension-style`
|`default`
a|[%hardbreaks]
`default`
`drop`
`indexify`
|The user-facing URL extension Antora uses for HTML pages.
See xref:playbook:urls-html-extension-style.adoc[].

|[[key]]`--key`
|Not set
|API key in the form `<name=value>`
|Can specify multiple times.
See xref:playbook:site-keys.adoc[] and <<ex-multiple-values>>.

|`--quiet`
|`false`
|<<boolean-value,Boolean>>
|Messages aren't written to stdout.

|[[redirect-facility]]`--redirect-facility`
|`static`
a|[%hardbreaks]
`disabled`
`httpd`
`netlify`
`nginx`
`static`
|See xref:playbook:urls-redirect-facility.adoc[] and <<ex-multiple-options>>.

|`--silent`
|`false`
|<<boolean-value,Boolean>>
|Suppresses all messages, including warnings and errors.

|[[start-page]]`--start-page`
|Not set
|Antora page ID
|See xref:playbook:site-start-page.adoc[].

|[[title]]`--title`
|Not set
|Title of the site
|See xref:playbook:site-title.adoc[] and <<ex-option-quotes>>.

|[[to-dir]]`--to-dir`
|[.path]_build/site_
|Filesystem path
|Be careful specifying this option in combination with `--clean`.
See xref:playbook:output-dir.adoc[] and <<ex-option-value>>.

|[[ui-bundle]]`--ui-bundle-url`
|Not set
|URL or filesystem path
|See xref:playbook:ui-bundle-url.adoc[] and <<ex-multiple-options>>.

|[[site-url]]`--url`
|Not set
|Absolute or pathname base URL of site
|See xref:playbook:site-url.adoc[] and xref:playbook:environment-variables.adoc[URL variable].
|===

== Pass options to the CLI

You can specify multiple options to a command.
A command must start with the xref:index.adoc#usage[antora base call] and end with the xref:index.adoc#specify-playbook[playbook file argument].
The xref:index.adoc#generate-command[generate command] is implied if not present, so it doesn't have to be specified explicitly.
Remember that the command you type executes relative to the xref:primer.adoc#working-directory[current working directory].

.Pass multiple options to the CLI
[listing#ex-multiple-options]
$ antora --ui-bundle-url ./../ui-bundle.zip --redirect-facility nginx --clean antora-playbook

In <<ex-multiple-options>>, the option `--ui-bundle-url` is assigned a value that specifies a local filesystem path relative to the working directory.
The `--redirect-facility` is assigned the built-in value `nginx`.
The <<boolean-value,boolean option>>, `--clean`, is enabled by entering its name without a value.

Some options can be specified multiple times.
These are keys that correspond to a map of values.
Examples include `--key` and `--attribute`.
Each value must be preceded by the option's flag.

.Specify an option multiple times
[listing#ex-multiple-values]
$ antora --key support=587tyr999 --key tracer=ID-${spawn} antora-playbook

In <<ex-multiple-values>>, the `--key` option has been assigned two values in <<name-value,the form name=value>>.

== Value types

There are two ways to assign a value to an option.
The option flag and its value can be written with a single space between them: `--option value`.
Or, it can be written using an equals sign (`=`) between the option flag and the value: `--option=value`.
Which form you choose is a personal preference.

In <<ex-option-value>>, the option `--to-dir` is assigned the value `prod`.
When Antora runs, a folder named [.path]_prod_ will be created relative to the working directory and the site files written to it.

.Assign a value to an option
[listing#ex-option-value]
$ antora --to-dir prod antora-playbook

Values that contain spaces must be surrounded by quotation marks: `--option 'Value with Spaces'` or `--option='Value with Spaces'`.
In <<ex-option-quotes>>, the option `title` is assigned the value `My Docs`.
The generated site's title will be _My Docs_.

.Assign a value containing spaces to an option
[listing#ex-option-quotes]
$ antora --title 'My Docs' antora-playbook

[#name-value]
=== Name=value values

The `--attribute` and `--key` options accept values in the form `name=value`, where `name` represents the name of the AsciiDoc attribute or API key, respectively.
In <<ex-name-value-pair>>, the attribute `page-team` is assigned the value `Coco B`.
The `@` at the end of the value indicates that the attribute is xref:ROOT:component-attributes.adoc#soft-set[soft set].

.Assign a name=value value to an option
[listing#ex-name-value-pair]
$ antora --attribute page-team='Coco B@' antora-playbook

[#boolean-value]
=== Boolean values

Boolean options turn a behavior on or off.
To activate a boolean option, type it on the command line.

.Activate a boolean option
[listing#ex-boolean-true]
$ antora --stacktrace antora-playbook

When a boolean option is activated in a playbook file, it can be overridden from the command line and deactivated with the `false` value.

.Deactivate a boolean option
[listing#ex-boolean-false]
$ antora --clean=false antora-playbook
