= Include an Example
:family: example
:coordinate: example$
:ext: .ext
:xrefstyle: short
:listing-caption: Example
:page-aliases: asciidoc:include-example.adoc
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-tags: {url-adoc-manual}/#by-tagged-regions
:url-indent: {url-adoc-manual}/#normalize-block-indentation

An example can be inserted into any page or partial in your site using the AsciiDoc include directive and the example's resource ID.

include::partial$include-directive.adoc[]

Antora supports filtering the lines of an example file by either line numbers using the `lines` attribute or tags using the `tag` or `tags` attributes.
Filtering by line numbers takes precedence.
See {url-adoc-manual}/#include-partial[the Asciidoctor documentation] for full details of the `lines`, `tag`, and `tags` syntax.

== Include an example from the same module

When the target example file and the current page belong to the same module, you only need to enter the family (`example$`) and resource coordinates in the resource ID.

.current-page.adoc
----
\include::example$helloworld.java[]
----

== Include an example from another module

When the target example file and current page belong to different modules of the same component version, enter the example's module, family (`example$`), and resource coordinates in the resource ID.

.current-page.adoc
----
\include::ROOT:example$output/query-max.json[]
----

== Include an example from another component

When the target example file and the current page belong to different docs components, enter the example's version, component, module, family (`example$`), and resource coordinates in the resource ID.

.current-page.adoc
----
\include::4.5@uml:admin:example$config.js[]
----

Don't specify the version coordinate if you want a page to always reference the latest version of the example.

.current-page.adoc
----
\include::uml:admin:example$config.js[]
----

//== Include a tagged region from an example

== Learn more

* xref:include-a-partial.adoc[Include a partial]
* xref:include-a-page.adoc[Include a standard page]
* xref:resource-id.adoc[Resource IDs]

.*Asciidoctor resources*
* {url-tags}[Select regions of content with tags^]
* {url-indent}[Normalize block indentation with indent^]
