= Include a Page
:family: page
:coordinate: page$
:ext: .adoc
:xrefstyle: short
:listing-caption: Example
:page-aliases: asciidoc:include-page.adoc
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-tags: {url-adoc-manual}/#by-tagged-regions
:url-leveloffset: {url-adoc-manual}/#include-partitioning

In Antora, the AsciiDoc include directive has been configured to include another page or portion of a page into the current page.
You can include a page from anywhere in the site, including pages from other docs components.

include::partial$include-directive.adoc[]

Antora supports filtering the lines of an include file by either line numbers using the `lines` attribute or tags using the `tag` or `tags` attributes.
Filtering by line numbers takes precedence.
See {url-adoc-manual}/#include-partial[the Asciidoctor documentation] for full details of the `lines` and `tag` or `tags` syntax.

== Include a page using a relative path

. On a new line, enter the name of the directive followed by two colons.
+
[subs=+quotes]
----
*include::*
----

. Next, enter the relative path of the target page in the target slot.
A relative path include is resolved from the current page (not the root of the pages family).
The relative path must be prefixed with `./`.
+
--
[subs=+quotes]
----
\include::**./relative-page-filename.adoc**[]
----

CAUTION: You may find that the relative path works without this prefix, but that could change in the future.
--

. Close the directive using a set of square brackets (`[]`).
+
[subs=+quotes]
----
include::./relative-page-filename.adoc**[]**
----

. The brackets may contain an optional list of attributes.
Attributes are entered as key-value pairs separated by commas.
+
--
[subs=+quotes]
----
\include::./relative-page-filename.adoc[**attribute,attribute**]
----

All the attributes (e.g., `lines`, `tags`, `leveloffset`, `indent`) on the include directive are supported.
--

== Learn more

* xref:page-partial.adoc[page-partial attribute]
* xref:resource-id.adoc[Resource IDs]
* xref:include-a-partial.adoc[Include a partial]
* xref:include-an-example.adoc[Include an example]

.*Asciidoctor resources*
* {url-tags}[Select regions of content with tags^]
* {url-leveloffset}[Offset section headings with leveloffset^]

////
== AsciiDoc include directive

In the simplest form, the target can be a path relative to the current page:

----
\include::./relative-page-filename.adoc[<attrlist>]
----

The target can also be a the resource ID of a page.
The resource ID ranges in scope from a page in the current module:

----
\include::page$page-filename.adoc[<attrlist>]
----

To a page in a different component version:

----
\include::version@component:module:page-filename.adoc[<attrlist>]
----

Let's explore the syntax of the include directive in detail.
////
