= Pages

== Source page to site page

Antora automatically generates one HTML site page for each source file assigned to the pages family.
Another way to think about this: one AsciiDoc page file in equals one HTML page out.

[#standard-page]
== Standard source pages

Page source files are plain text files marked up with the xref:asciidoc:asciidoc.adoc[AsciiDoc syntax] and saved with the file extension `.adoc`.
They're stored in a xref:ROOT:pages-directory.adoc[_pages_ family directory].

A xref:standard-page.adoc[standard page has a title and body content].
You can use just a little AsciiDoc syntax to mark up your pages, or you can explore the breadth of AsciiDoc and Antora's capabilities such as scoped attributes, including tagged regions from resources, and UI macros.

== Linking pages

Antora automatically publishes all of the standard source pages to your site, but if you want to create page-to-page links in the content, you'll need to learn about xref:page-id.adoc[Antora's page IDs] and how to create xref:page-id.adoc#whats-a-cross-reference[cross references].
You'll also use cross references and page IDs to build and organize your site's xref:navigation:index.adoc[component version page menus].
//If you don't want to include a page in a component menu, visitors will still be able to find it using search tools and through links to it on other pages, and in some scenarios, through dropdown menus such as the page version selector.
