= Assign UI Templates with page-layout

Antora provides a xref:page-attributes.adoc[page attribute] named `page-layout`.
This attribute applies an alternate UI layout to the contents of a page.

== page-layout attribute

The `page-layout` attribute is optional.
It's defined in the header of a page using an xref:define-and-modify-attributes.adoc#attribute-entry[AsciiDoc attribute entry].

[source]
----
= Page Title
:page-layout: tiles
----

The `page-layout` attribute accepts the filename of a UI layout file without the file extension.
For example, if you want a page to use the layout file [.path]_tiles.hbs_, assign the value `tiles` to `page-layout`.
The associated layout file (e.g., [.path]_tiles.hbs_) is expected to be located in the xref:antora-ui-default::templates.adoc[UI bundle's _layouts_ directory].
When the `page-layout` attribute is explicitly set in the header of a page, it overrides the default layout.

== Default page-layout

If `page-layout` isn't defined in a page's header, then the page layout defined by the xref:playbook:ui-default-layout.adoc[default_layout playbook key] is applied when the site is generated.
When neither `page-layout` or `default_layout` are set, Antora automatically assigns the built-in `default` value to `default_layout`.
The `default` page layout applies the [.path]_default.hbs_ layout file to any pages where `page-layout` isn't explicitly set.
