= Create a Start Page

You can create a start page named [.path]_index.adoc_ for a component version and Antora will automatically use it as the component version's default start page.
Or you can create a page with the filename of your choice, as long as you specify it as the component version's start page in the component version descriptor.

Visitors land on a component version's start page when they click on its entry in the xref:navigation:index.adoc#component-dropdown[component version selector] and when they click on its name at the xref:navigation:index.adoc#component-menu[top of the page menu].

[#use-default-start-page]
== Use a component version's default start page

To use Antora's default start page option, create an AsciiDoc source file named [.path]_index.adoc_ and save it in the xref:ROOT:pages-directory.adoc[_pages_ directory] of the xref:ROOT:root-module-directory.adoc[_ROOT_ module directory].
Structure and add content to [.path]_index.adoc_ like you would to any other page you write.
Antora will automatically set this page as the start page of the component version when the site is generated.

[#specify-start-page]
== Specify a start page for a component version

You can designate a specific page, regardless of its filename, to be a component version's start page.
*The source file must belong to the component version it will be the starting page for*, and it must be in the `pages` family.
Once you've created the page, assign it as the component version's start page using the xref:ROOT:component-start-page.adoc[start_page key] in [.path]_antora.yml_.

NOTE: The start page for a component version is separate from the start page for a site.
The start page for a site is where the visitor is directed when they go to the site's main URL.
To configure your site's start page, see xref:playbook:site-start-page.adoc[].
