= Navigation File Locations
:page-aliases: filenames-and-locations.adoc
:description: An overview of the purpose of an Antora navigation source file, its file format, its naming parameters, and storage location patterns.
// Filters
:page-collections: core concepts
:page-tags: docs component

[#storage]
== File location

A common pattern is for each module directory to contain its own navigation file.
xref:ROOT:module-directories.adoc#module[Modules already represent logical groups of concepts or objectives], so it's likely that you'd arrange the xrefs to that module's pages into a continuous, hierarchical flow of navigation menu entries.
This also reduces the number of coordinates the page IDs in the xrefs require when you add a page to the navigation file.

Navigation files should be stored at the base of a module directory, i.e., at the same level as a [.path]_pages_ family directory.
*Don't save navigation files inside a [.path]_pages_ folder*, otherwise the navigation files will be converted to pages and published as pages.

== Multiple files per module

A module directory can contain more than one navigation file.
This functionality helps you finely tune the navigation list order when you xref:register-navigation-files.adoc[register the navigation files] in an [.path]_antora.yml_ file.

== Alternative storage patterns

Storing a navigation file in the module it references simplifies the page cross references entered into it.
It also helps writers locate the navigation that's affected when they add pages to or remove pages from a module.
However, xrefs to other modules' pages (and even other component versions' pages) can be entered into any module's navigation file.
You just need to xref:page:module-and-page-xrefs.adoc#xref-page-across-modules[add the module coordinate] (or xref:page:version-and-component-xrefs.adoc[component name and version coordinates]) to the cross references you create in the navigation file.
For example, you could store a single navigation file in a component version's ROOT module, and, instead of having navigation files in each module in the component version, you could just add the cross references to pages in those other modules directly to the ROOT module's navigation file.

//A component menu is created when, at runtime, Antora combines one or more navigation files as instructed by a component descriptor file, converts the assembled navigation lists into HTML, wraps the HTML with a UI template, and publishes the resulting component navigation menus to your site.
//A component navigation menu allows site visitors to discover and navigate between a component's pages.
//Antora allows for a variety of use cases so that you can create, store, and assemble the navigation source files to suit your documentation requirements.
//The pages in the Site Navigation category describe the fundamentals of creating and storing navigation files in a documentation component.
// source nesting depth versus published nesting depth, titled versus non-titled lists
