= Configure Antora's Cache

== About Antora's cache

When Antora runs the first time, it will save resources it fetches over the network in a local cache.
Antora caches two types of resources:

* cloned git repositories
* downloaded UI bundles

Antora stores these resources in the cache directory, which are further organized under the [.path]_content_ and [.path]_ui_ folders, respectively.
The xref:playbook:runtime-cache-dir.adoc#default[default cache directory] varies by operating system.

== Override the default cache location

You can override the default cache location--listed here in order of precedence--using:

* the xref:cli:options.adoc#cache-dir[--cache-dir] option from the CLI,
* the xref:playbook:environment-variables.adoc[ANTORA_CACHE_DIR environment variable], or
* the xref:playbook:runtime-cache-dir.adoc[cache_dir key] in the playbook.

== Update the cache

If you want Antora to update the cache on subsequent runs, pass the xref:cli:options.adoc#fetch[--fetch option] to the Antora CLI or set the xref:playbook:runtime-fetch.adoc[fetch key] to `true` in the playbook.
This switch will force Antora to run a fetch operation on each repository it previously cloned.
It will also force Antora to download a fresh copy of the UI bundle, if the URL is remote and the xref:playbook:ui-bundle-url.adoc#snapshot[snapshot key] is `true`.

== Clear the cache

If you want to clear the cache altogether, locate the Antora cache directory on your system and delete it.
