= What's a Component Version?

== Component version

A [.term]*component version* represents a discrete version of the documentation for a project, product, library, service, training course, etc.
Antora looks for sources files associated with the same xref:component-name-and-version.adoc#name-key[component name] and xref:component-name-and-version.adoc#version-key[component version] in multiple content sources and collates them together to make a component version.
The xref:component-version-descriptor.adoc[component version descriptor] (named [.path]_antora.yml_) declares each component version and marks the source files that belong to it.
It also supplies additional configuration for that component version.

[#docs-component]
== Component

A [.term]*component*—more formally a *documentation component* or simply *docs component*—refers to all of the component versions that share the same xref:component-name-and-version.adoc#name-key[component name].
A component is never declared directly.
Instead, it gets created by having at least one component version.

////
move to better location

[#docs-component-vs-site]
== What's the difference between a docs component and a site?

A [.term]*documentation site* or *site* is a website generated by Antora and published to a directory or domain specified in a playbook.
A site typically consists of one or more docs components and each docs component consists of one or more component versions.
////
