= Content Source Versioning Methods
:page-aliases: component-versions.adoc

== Version content using branches

In this scheme, each branch in a git repository stores a xref:component-version.adoc[version of a component] just like we use branches to store versions of a software project.
The name of the branch itself doesn't matter.
It's the xref:component-name-and-version.adoc#version-key[version key] in the xref:component-version-descriptor.adoc[component version descriptor] that determines the version.

Branches are ideally suited for managing multiple versions of the same content.
If we didn't use branches to specify versions, but instead used, for example, version folders in a single branch, then we'd have to explicitly copy all the files from a previous version to start a new version.
And we'd have no easy way to compare, manage, and merge different instances of a document.

Branches handle this for us.
You simply create a new branch from an existing reference in the repository, and the repository only stores what's changed since that branch point.
That's what git does best.

== Version content using tags

Tags provide many of the same benefits of branches.
You can compare different instances of a file and the repository only stores what's changed since the previous tag point.

The downside of tags is that, once released, you can't update them (unlike branches).
So if you find a typo, or need to add an example, you can't edit the content in a released tag.
You'll need to release a new tag, or use another versioning method in combination with tags, in order to publish your updates.

If you do decide to take this approach, we recommend having separate tags for documentation that can be created after the tag for the software release is made (or else release the software _very_ frequently).

//== Version content using directories

== Learn more
// The list items IDs exist because they're the previous section IDs for sections that were originally in the aliased page, but have now become their own pages.

* xref:component-name-and-version.adoc[Define a component name and version with antora.yml]
* [[version-sorting]]xref:how-component-versions-are-sorted.adoc[How Antora sorts component versions]
* [[versionless-urls]]xref:component-with-no-version.adoc[Define a component version with no version]


////
This section is going to become a new page

== Setting the version for a branch

To assign a version to a component version stored in a particular branch, you set the xref:component-name-and-version.adoc#version-key[version key in the component version descriptor]:

[source,yaml]
----
name: versioned-component
version: '2.1'
title: Versioned Component
----

This component version descriptor communicates that the files taken from this branch contribute to the `2.1` version of the component named `versioned-component`.
The name of the branch where the component version's source files are stored could be _v2.1_ or _v2.1-beta_.
It doesn't matter.

The component version descriptor is the only file you have to update when creating a new branch.
All the page references for that component version should be relative to the version, so you shouldn't need to update any links.
The next time you run Antora on the repository, you'll see a new version in the component explorer drawer.

You may need to add the xref:playbook:configure-content-sources.adoc#branches[branch to your playbook file].
Keep in mind that content sources are filtered by branch name, not by the version they contain.
That's because xref::component-structure.adoc#distributed[a single component version's source files can be located in multiple branches, or even multiple repositories].
////
