= Distributed Component Versions

While all of a component version's source files are often stored in a single repository, it isn't a requirement.
Antora can collect source files that belong to the same component version from multiple repositories.

== What's a distributed component version?

When a component version's source files are stored in multiple repositories, it's referred to as a [.term]*distributed component version*.
// or, simply, a *distributed component*.

A common use case of a distributed component version is when most of its source files are stored in one repository, but a number of examples ([.path]_examples_ family directory) and tutorials ([.path]_pages_ family directory) are stored in another repository managed by a training team.
Antora has no problem combining the source files from both storage locations into a single component version.
This capability is provided by the simple, but-oh-so-powerful component version descriptor file, [.path]_antora.yml_.

== Managing antora.yml files and keys

Recall that an [.path]_antora.yml_ file specifies the component name and version of a component version.
If Antora discovers two or more [.path]_antora.yml_ files that specify an identical component name and version, it considers all of the files in the subsequent standard directory sets to belong to the same component version, even though the source files were collected from multiple locations.

When the source files of a component version are distributed, only one of the [.path]_antora.yml_ files should specify the optional configuration keys, such as `title` and `nav`, in addition to the required component `name` and `version`.
All of the other [.path]_antora.yml_ files that mark the locations of the component version's source files must only specify the component `name` and `version`.
Conflicting or duplicate optional configuration keys may produce unpredictable results.

== Managing modules and files

Antora will fail with an error if it finds two or more source files with identical filenames that belong to the same family and module in the distributed component version.
This also occurs if Antora discovers a module has two or more navigation files with identical filenames.

//== Playbook content source order
