= Family Directories and Families

Antora assigns preset, content-specific behavior to the source files stored in the family directories.

[#family-dir]
== What's a family directory?

A [.term]*family directory* groups source files that share the same function, processing requirements, and publishing rules.
Certain families, like the page family, require that all files share the same file extension (e.g., _.adoc_).

Antora recognizes five standard family directories: [.path]_attachments_, [.path]_examples_, [.path]_images_, [.path]_pages_, and [.path]_partials_.

----
📒 repository
  📄 antora.yml
  📂 modules
    📂 a-named-module
      📂 attachments
      📂 examples
      📂 images
      📂 pages
      📂 partials
----

A family directory can only be stored in a xref:module-directories.adoc#module-dir[module directory].
At runtime, Antora collects the source files stored in the family directories and assigns them to a <<family,family>> within a xref:module-directories.adoc#module[module] and xref:component-version.adoc[component version].

[#family]
== What's a family?

A [.term]*family* is a classification Antora applies to content collected from a family directory.
The family corresponds to the name of the <<family-dir,family directory>>.
Content is configured, converted, and published according to the preset behavior associated with its assigned family.

The families are:

* xref:attachments-directory.adoc[attachments]
* xref:examples-directory.adoc[examples]
* xref:images-directory.adoc[images]
* xref:pages-directory.adoc[pages]
* xref:partials-directory.adoc[partials]

////
For instance:

* Full page AsciiDoc documents go in the [.path]_pages_ directory.
* Photographs, diagrams, screenshots, and other graphics go in the [.path]_images_ directory.
* Source code snippets and terminal output go in the [.path]_examples_ directory.
* Reusable, AsciiDoc content snippets, such as product descriptions and definitions, go in the [.path]_partials_ directory.
////
