= Install and Run Antora Quickstart
:listing-caption!:
:url-demo: https://gitlab.com/antora/demo

This quickstart walks you through the general steps required to install Antora and generate a basic documentation site.

On this page, you’ll learn:

* [x] How to install Node.js.
* [x] How to install the Antora.
* [x] How to create your first Antora playbook.
* [x] How to run Antora and generate a site using a playbook.

[#install-nodejs]
== Install Node.js

Antora requires an active long term support (LTS) release of Node.js.
To see if you have Node installed, and which version, open a terminal and type:

 $ node --version

This command should return an {url-node-releases}[active Node LTS version number].

[subs=attributes+]
....
$ node --version
v{version-node}
....

If you have an active Node LTS version on your machine, you're ready to <<install-antora,install Antora>>.

If *no version number is displayed in your terminal*, you need to install Node.

* xref:install:linux-requirements.adoc#install-nvm[Install nvm and Node on Linux]
* xref:install:macos-requirements.adoc#install-nvm[Install nvm and Node on macOS]
* xref:install:windows-requirements.adoc[Install nvm and Node on Windows]

If *you have Node installed, but it isn't an active LTS version*, you need to upgrade Node.
To upgrade to the latest Node LTS version and set it as your default version, type the following commands in your terminal:

.Linux and macOS
[subs=attributes+]
----
$ nvm install --lts
$ nvm alias default {version-node-major}
----

.Windows
[subs=attributes+]
----
$ nvm install {version-node}
$ nvm alias default {version-node}
----

Once you've installed Node, it's time to install Antora.

[#install-antora]
== Install Antora

Before installing Antora, make a new directory for your site named [.path]_docs-site_ and switch to it.

 $ mkdir docs-site
 $ cd docs-site

To generate documentation sites with Antora, you need the Antora command line interface (CLI) and the Antora site generator.
Let's install these packages globally to make them available on your PATH:

 $ npm i -g @antora/cli @antora/site-generator-default

Verify the `antora` command is now available on your PATH by running:

 $ antora -v

If the installation was successful, the command should report the latest, stable version of Antora.

[subs=attributes+]
....
$ antora -v
{page-component-version}.x
....

Now you're ready to create your first playbook.

TIP: See xref:install:install-antora.adoc[Install Antora] for more detailed information and additional installation methods.

== Create a playbook

To produce a documentation site, Antora needs a playbook.
Using your preferred text editor or IDE, create a new file and populate it with the configuration information <<demo-playbook,listed below>>.
Save this file as [.path]_antora-playbook.yml_ in the [.path]_docs-site_ directory you made in the previous step.
This playbook file will create a site using the {url-demo}[Antora demo repositories].

[#demo-playbook]
.antora-playbook.yml
[source,yaml]
----
site:
  title: Antora Docs
  start_page: component-b::index.adoc # <1>
content:
  sources: # <2>
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: master
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui: # <3>
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
----
<1> A page from a component version to be used as the home page for your site.
<2> The `sources` category contains the list of git repository locations, branch name patterns, and other repository properties that Antora uses when aggregating the site content.
<3> The `ui` category contains keys that specify the location of the UI bundle and how it should be processed.

TIP: See the xref:playbook:index.adoc[Antora playbook] for more detailed information about the playbook file.

== Run Antora

To generate the site, point the `antora` command at your playbook file.
In the terminal, make sure you're in [.path]_docs-site_ directory, then type:

 $ antora --fetch antora-playbook.yml

Antora will clone the content and UI repositories and generate your documentation site to the default output directory.

IMPORTANT: By default, Antora does not sync the repository once it clones it.
Instead, it tries to work offline by using the repository in the cache it previously cloned.
This default can create some confusion when getting started.
Therefore, we recommend including the xref:playbook:runtime-fetch#fetch-option[`--fetch` option] in the command until you're more familiar with Antora.
You can also set the xref:playbook:runtime-fetch#fetch-key[fetch key] in your playbook to enable this setting permanently.

Navigate to the [.path]_docs-site/build/site_ directory and open the [.path]_index.html_ file in your browser to see the result.
Congratulations!
You've successfully built your first site with Antora.

TIP: For more detailed information about running Antora and troubleshooting help, see xref:run-antora.adoc[Run Antora to generate your site].

== Learn more

* Learn how to xref:organize-content-files.adoc[organize your content files] for Antora.
