= Module Segment in Page URLs
:xrefstyle: short
:listing-caption: Example

[#root-module-urls]
== URLs for ROOT module pages

When a ROOT module's xref:pages-directory.adoc[pages] are published to a site, they become the top-level pages of their assigned xref:component-version.adoc[component version].
That means the xref:root-module-directory.adoc[module name], _ROOT_, never appears in the page's URL.

To demonstrate this concept, let's compare the URLs of two pages, one assigned to a ROOT module and one assigned to a named module.
The xref:standard-directories.adoc[set of standard directories] illustrated in <<ex-modules>> contains content source files for a project named _Hyper Lemur_.

[#ex-modules]
.Two module directories containing content that's part of the Hyper Lemur project
----
📒 repository
  📄 antora.yml
  📂 modules
    📂 admin
      📂 pages
        📄 user-management.adoc
      📄 nav.adoc
    📂 ROOT
      📂 images
      📂 pages
        📄 deploy.adoc
        📄 index.adoc
      📄 nav.adoc
----

Notice the file named [.path]_deploy.adoc_ in the [.path]_pages_ folder inside the [.path]_ROOT_ module folder.
When Antora generates a site for Hyper Lemur, the URL for the page created from the [.path]_deploy.adoc_ source file will look like this.

image::root-page-url.svg[ROOT module page URL,role=grow-x]

The base URL, _\https://my-company.com_, xref:playbook:site-url.adoc[is set in the playbook] that Antora used to generate the site.
The component name segment, _hyperlemur_, and version segment, _1.0_, are set in the xref:component-version-descriptor.adoc[component version descriptor].
The page segment, _deploy_, is the family-relative path of the AsciiDoc source file [.path]_deploy.adoc_.
The name of the module, _ROOT_, isn't used in the URL.

Now, let's see what the URL of a page stored in the named module, _admin_, would look like.

[#named-module-urls]
== URLs for named module pages

Using the Hyper Lemur source files in <<ex-modules>>, let's see what the URL for the [.path]_user-management.adoc_ file would look like.
The file is assigned to the _pages_ family of the _admin_ module.

//.URL for user-management.adoc page in a-module
image::module-page-url.svg[Named module page URL,role=grow-x]

Notice that the xref:named-module-directory.adoc#named-module[name of the module], _admin_, is in the URL directly after the component's version.
