= Named Module Directory
:xrefstyle: short
:listing-caption: Example

== What's a named module directory?

Named module directories are xref:module-directories.adoc#module-dir[optional module directories] that are located in a xref:module-directories.adoc#modules-dir[_modules_ directory].
You can create as many named module directories as you need.

[#ex-named]
.Named module directories
----
📒 repository
  📂 docs <1>
    📄 antora.yml <2>
    📂 modules <3>
      📂 a-named-module <4>
        📂 pages <5>
          📄 a-source-file.adoc <6>
        📄 nav.adoc <7>
      📂 get-started <8>
        📂 pages
          📄 a-source-file.adoc
----
<1> Content source root
<2> Required [.path]_antora.yml_ file
<3> Required [.path]_modules_ directory
<4> A named module directory
<5> [.path]_pages_ family directory
<6> A source file for a page
<7> A navigation file
<8> Another module directory, named [.path]_get-started_

Antora uses a module's directory name to create a <<named-module,module's name>>.
For this reason, it's important to carefully consider xref:module-directory-names.adoc[what you name your named module directories].
At a minimum, a named module directory must contain at least one xref:family-directories.adoc[family directory] with at least one source file.
A named module directory can also contain an optional navigation file.

[#named-module]
== What's a named module?

Source files in each named module directory become part of a named module in a xref:component-version.adoc[component version].
The name of a module corresponds to the name of a module directory.
For instance, source files stored in the [.path]_get-started_ module directory shown in <<ex-named>> will be assigned to the module `get-started`.

[#where-name-is-used]
== Where's a module's name used?

When you target content that belongs to a named module from another module or component version, you'll specify the module's name in the  xref:page:page-id.adoc[page IDs] of cross references and the xref:page:resource-id.adoc[resource IDs] for images, examples, and partials.

The module's name is also used as a xref:module-url-segment.adoc#named-module-urls[segment in page URLs].
