= Partials Directory and Files

[#partials-dir]
== Partials family directory

A module directory can contain an xref:family-directories.adoc[optional family directory] named [.path]_partials_.

----
📂 modules
  📂 ROOT
    📂 pages
      📄 a-source-file.adoc
    📂 partials <1>
      📄 a-source-file.adoc <2>
    📄 nav.adoc
----
<1> A [.path]_partials_ family directory in a [.path]_ROOT_ module directory
<2> A partial source file

Antora applies preset behavior to the source files stored in the [.path]_partials_ directory when it generates a site.

[#partials]
== Partials

xref:page:partials-and-content-snippets.adoc[Partials] are resources that contain content snippets, such as common descriptions, terminology, or reference tables, that you plan to reuse in one or more pages.
Partials are saved as AsciiDoc source files (_.adoc_) and stored in a [.path]_partials_ directory.

If a partial isn't referenced in an AsciiDoc include directive, its content won't be published to a site.
Partials and tagged regions in a partial can be inserted into any page, regardless of the module or component version that page belongs to, using the xref:page:include-a-partial.adoc[include directive] and the partial's xref:page:resource-id.adoc[resource ID].

When referencing a partial, the `partial$` family coordinate must be included in its resource ID.
This coordinate is required because the include directive is also used to reference xref:examples-directory.adoc[examples] and, occasionally, xref:pages-directory.adoc[pages].
