= Run Antora to Generate Your Site
:navtitle: Run Antora
:listing-caption!:
:url-demo: https://gitlab.com/antora/demo
:url-demo-project: {url-demo}/docs-site
:url-demo-playbook: {url-demo-project}/raw/master/antora-playbook.yml
:url-demo-component-a: {url-demo}/demo-component-a
:url-demo-component-b: {url-demo}/demo-component-b
:url-default-ui: https://gitlab.com/antora/antora-ui-default

Assumptions:

* [x] You've xref:install:install-antora.adoc[installed the Antora CLI and a site generator pipeline].
* [x] You have your own xref:playbook:index.adoc[playbook], or you're using the Demo playbook.
* [x] Your playbook is configured to access at least one of your own  xref:content-source-repositories.adoc[repositories containing content source files] or Antora's Demo content repositories.
* [x] Your playbook is configured to use a xref:playbook:configure-ui.adoc[custom UI bundle or Antora's default UI bundle].

On this page, you'll learn:

* [x] How to run Antora and generate a site.

== Antora demo playbook and content repositories

You don't need to set up a playbook file, xref:component-version.adoc[component version], or UI to evaluate Antora.
Instead, you can use the Antora demo playbook and content repositories.

The demo consists of a {url-demo-project}[playbook repository] containing a playbook file and content repositories ({url-demo-component-a}[component-a] and {url-demo-component-b}[component-b]) to which that playbook refers.
It also uses the UI bundle produced by the {url-default-ui}[default UI project].

Once you've xref:install:install-antora.adoc[installed Antora], you can run Antora using the demo materials to explore its capabilities.
The instructions and examples on this page will guide you through the process.

== Choose a playbook

To produce a documentation site, Antora needs a playbook.
But first, you'll need to create or choose a directory where you'll store the playbook and where the generated site files will be saved (assuming you use the default output configuration).

For the examples on this page, we'll use the demo playbook and content repositories.

. Open a terminal and make a new directory named [.path]_demo-site_.

 ~ $ mkdir demo-site

. Switch (`cd`) into the directory you just made.

 ~ $ cd demo-site

. Using your preferred text editor or IDE, create a new playbook file named [.path]_antora-playbook.yml_ and populate it with the contents of the following example.
Or, you can download {url-demo-playbook}[the playbook file] from the demo project repository.
+
.antora-playbook.yml
[source,yaml]
----
site:
  title: Antora Demo Site
  url: https://my-antora-demo-site.org # <1>
  start_page: component-b::index.adoc # <2>
content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: master
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
----
<1> The 404 page and sitemap files are only generated if the site `url` key is set.
The sitemap files are only generated if the value of the site `url` key is an absolute URL.
<2> The site `start_page` key accepts the same page ID syntax that's used in xrefs.

. Save the playbook as [.path]_antora-playbook.yml_ in the [.path]_demo-site_ directory you made in Step 1.

== Run Antora

. To generate the site with the default Antora site generator, point the `antora` command at your playbook file.
In the terminal, type:
+
--
 demo-site $ antora antora-playbook.yml

Antora will clone the content repositories.
The cloning progress of each repository is displayed in the terminal.

.Repository cloning progress
....
[clone] https://gitlab.com/antora/demo/demo-component-a.git [################]
[clone] https://gitlab.com/antora/demo/demo-component-b.git [################]
....

Once cloning is complete, Antora converts the AsciiDoc pages to embeddable HTML, wraps the HTML in the UI page templates, then assembles the pages into a site under the destination folder, which defaults to _build/site_.
--

. Antora has completed generation when the command prompt (`$`) reappears in the terminal.
+
[TIP#error-stacktrace]
====
If something goes wrong during generation, you'll see an error message in the terminal.

....
error: a message that summarizes what went wrong
....

If this message does not provide enough information to fix the problem, you can ask Antora for more context.
To tell Antora to reveal the calls leading up to the error (i.e., the stacktrace), run the `antora` command again, this time with the `--stacktrace` option:

 demo-site $ antora --stacktrace antora-playbook.yml

Share this stacktrace when xref:project/get-help.adoc[asking for help].
====

. Switch into the site folder (`cd`) and list (`ls`) its contents.
+
--
 demo-site $ cd build/site/

Inside the [.path]_build/site_ folder, run:

 site $ ls -1

You should see the following list of files and directories:

....
_
404.html
component-a
component-b
index.html
sitemap-component-a.xml
sitemap-component-b.xml
sitemap.xml
....

NOTE: The 404 page and sitemap files will be missing if the `site.url` property is not defined in your playbook.
The main sitemap file is actually a sitemap index.
That file links to the sitemap for each component, which is where the URL for the individual pages can be found.

This list includes the entry point of your documentation site, [.path]_index.html_.
--

. On some operating systems, you can open the site directly from the command line by typing `open`, followed by the name of the HTML file.
+
--
 site $ open index.html

Or, you can navigate to an HTML page inside the destination folder in your browser.
If you've been following along with the Demo materials, once you find the demo-site directory, navigate to the file [.path]_build/site/index.html_.
--

[#using-private-repositories]
== Private git repositories

Antora can authenticate with private repositories using HTTP Basic authentication over HTTPS.
See xref:playbook:private-repository-auth.adoc[Private repository authentication] to learn more.


////
The script loads and executes Antora and passes any trailing configuration flags and switches.

#Move this to a fragment or file in the playbook module#
For example, you can specify a custom playbook as follows:

 $ node generate --playbook=custom-site

Depending on your internet connection speed, it may take anywhere from a few seconds to several minutes to complete the generation process the first time you run it.
That's because, first, Antora has to download (i.e., `git clone`) all the repositories specified in the playbook.

When you run Antora again, the repositories are automatically updated (i.e., `git pull`).
These subsequent runs complete much faster because only the changes to the repositories have to be downloaded.

The repositories are cached under the [.path]_build/sources/_ directory.
If you remove the [.path]_build/_ directory, the repositories will have to be downloaded again from scratch.
////
