= UI Keys

The playbook keys configured under `ui` define the location of the UI bundle and control how it's processed.

[#ui-key]
== ui key

The `ui` key specifies the UI bundle's location, state, default page template name, and output directory.

.antora-playbook.yml
[source,yaml]
----
ui: # <1>
  bundle: # <2>
    url: https://example.org/docs-ui/download/latest/ui-bundle.zip # <3>
    snapshot: true # <4>
    start_path: dark # <5>
  default_layout: base # <6>
  output_dir: _/dark # <7>
----
<1> Required `ui` key
<2> Required `bundle` key
<3> Required `url` key
<4> Optional `snapshot` key
<5> Optional `start_path` key
<6> Optional `default_layout` key
<7> Optional `output_dir` key

The `ui`, `bundle`, and `url` keys are required.
Alternatively, the `url` key can be assigned from the xref:cli:options.adoc#ui-bundle[CLI].
The other keys are optional; Antora will use their default values if they're not specified.

[#ui-reference]
== Available UI keys

[cols="3,6,1"]
|===
|UI Keys |Description |Required

|xref:ui-bundle-url.adoc#snapshot[bundle.snapshot]
|Indicates whether the URL points to a snapshot.
|No

|xref:ui-bundle-url.adoc#start-path-key[bundle.start_path]
|Accepts a path inside the UI bundle from which files should be selected.
|No

|xref:ui-bundle-url.adoc[bundle.url]
|Accepts a URL or filesystem path to a UI bundle archive.
|Yes

|xref:ui-default-layout.adoc[default_layout]
|Applies a layout template to pages that don't specify a page layout.
|No

|xref:ui-output-dir.adoc[output_dir]
|Accepts a filesystem path to the output directory where Antora writes the published site's UI files.
|No

|supplemental_files
|Supplemental file list or a directory of files to append to the UI bundle.
|No
|===

//supplemental_files: ./supplemental-ui
