= Filesystem Provider
:xrefstyle: short
:listing-caption: Example

In order to publish a site to multiple  destinations, including one or more filesystem destinations, your playbook must set the `output`, `destinations` and `provider` keys.

[#fs-provider]
== fs provider

The `provider` value `fs` publishes the site to a directory on a filesystem.
It's the formal equivalent to specifying the output directory using the `dir` key.

.antora-playbook.yml
[source,yaml]
----
output:
  destinations: # <1>
  - provider: fs # <2>
----
<1> The `provider` key must be configured under the `destinations` key.
<2> Under `destinations`, type a hyphen (`-`) and a blank space, then the key name `provider`, followed by a colon (`:`).
After the colon, enter a blank space, and then the built-in value name `fs`.

Unless the `path` key or xref:output-dir.adoc[dir key] is specified, the default path for the `fs` provider is [.path]_build/site_.

[#path-key]
== path key

The optional `path` key designates the target location where the output files are to be written.
The `fs` provider treats this value as a target directory.

The `path` key accepts a relative or absolute filesystem path.
The provider will create any interim directories as needed.
include::partial$relative-path-rules.adoc[]

If `path` isn't specified, it gets populated with the default value, [.path]_build/site_, or, in the case of the first `fs` provider, the value of `dir`.
When the xref:output-dir.adoc[dir key] is specified, its value is assigned to (or overrides) the first `fs` provider `path`.
When the output directory is specified from the CLI using the xref:cli:options.adoc#to-dir[--to-dir option], it also overrides the first `fs` provider `path` (as well as `dir`) in a playbook.

[#relative-path]
=== Specify a relative path

In <<ex-rel>>, the site will be published to a folder named [.path]_launch_ relative to the playbook file.

[#ex-rel]
.Assign a relative path
[source,yaml]
----
output:
  destinations:
  - provider: fs
    path: ./launch
----

[#absolute-path]
=== Specify an absolute path

In <<ex-abs>>, the site will be published to [.path]_home/dev/site/beta_, regardless of where the playbook is located.

[#ex-abs]
.Assign an absolute path
[source,yaml]
----
output:
  destinations:
  - provider: fs
    path: /home/dev/site/beta
----

[#clean-key]
=== clean key

The `clean` key is optional and is deactivated (assigned the value `false`) by default.
It can be applied as part of an `fs` provider configuration instead of xref:output-dir.adoc#clean-key[directly under the output key].

.antora-playbook.yml
[source,yaml]
----
output:
  destinations:
  - provider: fs
    path: /home/dev/site/beta
    clean: true # <1>
----
<1> `clean` is activated with the value `true` and deactivated with `false`.

When `clean` is assigned the value `true`, it removes the destination `path` recursively before generating the site.
This key only applies to the `fs` provider.

[#clean-warning]
WARNING: Use this key with great care.
For example, if you set `path` to your [.path]_home_ directory and `clean` to `true`, you'll delete ALL of the folders and files in [.path]_home_.

include::page$output-provider-archive.adoc[tag=multiple]
