= Output Directory
:xrefstyle: short
:listing-caption: Example

The `dir` key specifies the directory where the generated site files are published.
It provides a simpler way to use the default `fs` provider without having to set the more formal `destinations` and `provider` keys.

[#default]
== Default output directory

The default output directory is [.path]_build/site_.
If `dir` isn't set and an `fs` provider `path` isn't specified, the site files are written to this default directory.

[#dir-key]
== dir key

The `dir` key is configured under the xref:configure-output.adoc#output-key[output key] in a playbook.
The `dir` key specifies the directory where the generated site files are published.
It accepts a relative or absolute filesystem path.
include::partial$relative-path-rules.adoc[]

The `dir` key can be used in combination with the xref:configure-output.adoc#destinations-key[destinations key].
If both an `fs` provider `path` and `dir` are specified, the value assigned to `dir` overrides xref:output-provider-fs.adoc#path-key[the first fs provider path].
When the output directory is specified from the CLI using the xref:cli:options.adoc#to-dir[--to-dir option], it also overrides the `dir` and first `fs` provider `path` in a playbook.

[#relative-path]
=== Specify a relative path

In <<ex-rel>>, the site will be published to a folder named [.path]_launch_ relative to the playbook file.

[#ex-rel]
.Assign a relative path to the dir key
[source,yaml]
----
output:
  dir: ./launch
----

[#absolute-path]
=== Specify an absolute path

In <<ex-abs>>, the site will be published to [.path]_home/dev/docs-site/beta_, regardless of where the playbook is located.

[#ex-abs]
.Assign an absolute path to the dir key
[source,yaml]
----
output:
  dir: /home/dev/docs-site/beta
----

[#clean-key]
== Clean the output directory

The `clean` key is optional and is deactivated (assigned the value `false`) by default.
When it's assigned the value `true` in a playbook, it removes the path assigned to `dir` recursively before generating the site.

[#ex-clean]
.Activate the clean key
[source,yaml]
----
output:
  clean: true # <1>
----
<1> `clean` is activated with the value `true` and deactivated with `false`.

This key only applies to the filesystem provider.

[#clean-warning]
WARNING: Use this key with great care.
For example, if you set `dir` to your [.path]_home_ directory and `clean` to `true`, you'll delete ALL of the folders and files in [.path]_home_.

The `clean` key can also be activated via the CLI using the xref:cli:options.adoc#clean[--clean option].
