= Fetch Updates

Use the `fetch` key whenever you want to retrieve updates from the remote content sources repositories and UI bundle snapshots.

== Fetch operations

Activating the `fetch` key from a playbook or the CLI causes Antora to perform both of the following actions each time it runs:

. Run a fetch operation on all cloned, remote content sources repositories.
. Download the remote UI bundle if it's marked as a xref:ui-bundle-url.adoc#snapshot[snapshot].

[#fetch-key]
== fetch key

The first time Antora runs, it caches any remote content sources git repositories and UI bundles.
On subsequent runs, Antora resolves these resources in the cache folder, effectively running offline.
You can tell Antora to refresh the cache by setting the `fetch` key to `true`.
The optional `fetch` key is configured under the xref:configure-runtime.adoc[runtime key] in a playbook.

.antora-playbook.yml
[source,yaml]
----
runtime:
  fetch: true
----

== Fetch option

You don't have to modify the playbook file directly to set this key.
You can use the `--fetch` option from the xref:cli:options.adoc#fetch[CLI].

 $ antora --fetch antora-playbook.yml

The `--fetch` option overrides the value assigned to the `fetch` key in the playbook file.
