= Site Start Page

When you assign a valid page ID to the `start_page` key in your playbook, site visitors will be redirected from the site's index page at the xref:site-url.adoc[site URL] to the URL of the start page.

[#start-page-key]
== start_page key

The `start_page` key is optional.
It's configured under the xref:configure-site.adoc[site key] in a playbook.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://example.org
  start_page: component:module:filename.adoc
----

You can use any page that belongs to a component version as the index page for your site.
The `start_page` key accepts a xref:page:page-id.adoc[page ID] as a value.
*The page ID must include the component, module, and page coordinates*.
The version coordinate can be specified if you want to use a specific version of a page instead of the latest version.
Alternatively, `start_page` can be assigned from the xref:cli:options.adoc#start-page[CLI].

== Use a page's latest version

To have the `start_page` key always point to the last version of the specified page, don't enter the version coordinate in the page ID.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: component-b::index.adoc
----

For this example, let's say that version 2.0 is the latest version of Component B.
In this case, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/2.0/index.html_.

== Use a specific version of a page

If you want the site's start page to be a specific version of the designated page, include the xref:page:page-id.adoc#id-version[version coordinate in the page ID].

.antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: 1.0@component-b::index.adoc
----

In this example, _\https://demo.antora.org/index.html_ will redirect to _\https://demo.antora.org/component-b/1.0/index.html_.

NOTE: To configure a start page for a component version, see xref:ROOT:component-start-page.adoc[].
