= Robots
:url-robots-standard: https://en.wikipedia.org/wiki/Robots_exclusion_standard

Antora can generate a {url-robots-standard}[robots.txt file] to control which paths site crawlers can visit.

[#robots-key]
== robots key

The `robots` key is optional.
It's configured under the xref:configure-site.adoc[site key] in a playbook.
Its accepted values are:

`allow`:: Allow all user agents to access all paths in the published site.
`disallow`:: Disallow all user agents from accessing all paths in the published site.
custom multi-line string:: Non-empty, user-specified string that's used as the contents of the generated [.path]_robots.txt_ file.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://example.org
  robots: disallow
----

Antora will generate the [.path]_robots.txt_ file at the root of the site.

The `robots` key depends on the sibling `url` key.
If the `url` key isn't assigned a value, Antora won't generate a [.path]_robots.txt_ file even if `robots` is set to an allowable value.

[#allow-or-disallow-robots]
== Assign allow or disallow to robots

Let's assume the `url` and `robots` keys are defined as follows:

.antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  robots: allow
----

This will generate a [.path]_robots.txt_ file that allows user agents access to all of the site's paths.

.Generated robots.txt
....
User-agent: *
Allow: /
....

Similarly, if the `url` and `robots` keys are defined as follows:

.antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  robots: disallow
----

This will generate a [.path]_robots.txt_ file that disallows access to all paths.

.Generated robots.txt
....
User-agent: *
Disallow: /
....

== Generate robots.txt with custom content

Any other non-empty value assigned to `robots` will be used as the contents of the [.path]_robots.txt_ file.
For example, let's assume the `robots` key is declared as follows:

.antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  robots: |
    User-agent: *
    Disallow: /private/
----

This will result in the following [.path]_robots.txt_ file being generated.

.Generated robots.txt
....
User-agent: *
Disallow: /private/
....
