= Default Layout for Pages

[#default]
== Default page layout

Unless the `default_layout` key is specified in the playbook, Antora applies the `default` layout to any page where the `page-layout` attribute isn't set.
The `default` layout corresponds to the [.path]_default.hbs_ file that Antora expects to find in the [.path]_layouts_ directory of the UI bundle.

You can instruct Antora to apply a custom layout to all of the pages in a site with the `default_layout` key.
//A default page layout can be applied to all pages that don't have a layout explicitly assigned in the page header (using the `page-layout` attribute).
//If not specified, this key defaults to the value `default`.

[#default-layout-key]
== default_layout key

The `default_layout` key is mapped to the `ui` key.
It accepts a value that's the stem of a layout file (i.e., the name of the file without the file extension).
The specified layout file is expected to be located in the UI bundle's [.path]_layouts_ directory.

For example, if you want the layout file [.path]_article.hbs_ to be used as the default page layout, you'd set `default_layout` to `article`.

.Default layout value
[source,yaml]
----
ui:
  bundle:
    url: ./../docs-ui/build/ui-bundle.zip
  default_layout: article
----

The layout `article` will be applied to every page in the site, except for any page that has the xref:page:page-layout.adoc[page-layout attribute defined in its header].
