= UI Output Directory

[#default]
== Default UI output directory

The UI files are published to a directory labeled with a single underscore, [.path]_++_++_ , located relative to the site's xref:output-dir.adoc[output directory].
For instance, when the site is published to the default site output directory ([.path]_build/site_), and no UI `output_dir` is specified, the UI files are written to [.path]_++build/site/_++_.

[#output-dir-key]
== output_dir key

The `output_dir` key allows you to specify an alternate directory where Antora should publish the UI files.
The path is relative to the root of the published site.

.Relative UI output path
[source,yaml]
----
ui:
  bundle:
    url: /home/user/projects/docs-ui/build/ui-bundle-with-themes.zip
    start_path: dark
  output_dir: _/dark
----

In this example, the site will be written to the default destination directory, therefore, the UI files will be published [.path]_++build/site/_/dark++_.

Antora will automatically reconfigure all references to the UI files, regardless of what value you use.
This is thanks in part to the use of the `+{{uiRootPath}}+` placeholder in the UI templates.

In the next example, the site's output directory (`dir`) is specified in addition to the UI output directory.

.Custom site and UI output directories
[source,yaml]
----
ui:
  bundle:
    url: /home/user/projects/docs-ui/build/ui-bundle-with-themes.zip
    start_path: dark
  output_dir: _/dark
output:
  dir: ./public
----

The UI files will be published to [.path]_++public/_/dark++_.
