= HTML Extension Styles

[#html-extension-style-key]
== html_extension_style key

The `html_extension_style` key is optional.
It's configured under the xref:configure-urls.adoc[urls key] in a playbook.

.antora-playbook.yml
[source,yaml]
----
urls:
  html_extension_style: indexify
----

It accepts the following built-in values:

`default`:: Published page URLs are displayed with the _.html_ extension, i.e., [.path]_\https://base-url.com/component/version/module/my-file.html_.
Antora automatically applies this style when `html_extension_style` isn't set in the playbook or via the CLI.

`drop`:: The _.html_ extension is dropped from the end of the published page URLs, i.e., [.path]_\https://base-url.com/component/version/module/my-file_.

`indexify`:: The _.html_ extension is dropped and a forward slash (`/`) is appended to the end of the published page URLs, i.e., [.path]_\https://base-url.com/component/version/module/my-file/_.

[#default]
== Using the default style

Antora will automatically assign the value `default` to the `html_extension_style` key at runtime if it isn't set in the playbook or in the CLI using the xref:cli:options.adoc#html-extension[--html-url-extension-style option].
The default style appends the _.html_ extension to the end of every published page's URL.
For example, the resulting URL for the page [.path]_my-file.adoc_ would be displayed in a browser with _.html_ appended to the end, i.e., [.path]_\https://base-url.com/component/version/module/my-file.html_.

[#indexify-style]
== Apply the indexify style

Let's assign `indexify` to the `html_extension_style` key.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://example.org
urls:
  html-extension-style: indexify
----

When `indexify` is applied, the site's published URLs don't end with the extension _.html_.
Instead, a forward slash (`/`) is appended directly to the end of the page stem.
This results in the URL for the page [.path]_my-file.adoc_ to be displayed in a browser as [.path]_\https://example.com/component/version/module/my-file/_.

To locally preview all the features of a site, such as redirects and the 404 page, when `html_extension_style` is assigned `indexify`, you'll need to xref:ROOT:preview-site.adoc[run a local server].

[#drop-style]
== Apply the drop style

Let's assign `drop` to the `html_extension_style` key.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://example.org
urls:
  html-extension-style: drop
----

When `drop` is applied, the site's published URLs don't end with the extension _.html_.
This results in the URL for the page [.path]_my-file.adoc_ to be displayed in a browser as [.path]_\https://example.com/component/version/module/my-file_.

To locally preview all the features of a site, such as redirects and the 404 page, when the style is `drop`, you'll need to xref:ROOT:preview-site.adoc[run a local server].
