= Customize reftext and navtitle
:listing-caption: Example
:xrefstyle: short

The `reftext` and `navtitle` attributes are automatically set and assigned default values when Antora runs.
You can customize the values of these attributes by setting them in the header of a page.

[#reftext]
== reftext attribute

A target page's `reftext` value is used as the link text in an xref that originates from a page or resource file.
By default, Antora assigns a page's title to the `reftext` attribute at runtime.
In <<ex-page>>, let's reference the [.path]_install-prerequisites.adoc_ file and leave the link text field empty.

[#ex-page]
.current-page.adoc
[source]
----
Make sure you xref:install-prerequisites.adoc[].
----

Now, let's look at the header of the [.path]_install-prerequisites.adoc_ file.

[#ex-default-reftext]
.install-prerequisites.adoc
[source]
----
= Installing and Testing Silver Leaf's Prerequisites

Here are the prerequisites:
----

Notice in <<ex-default-reftext>> that `reftext` isn't set in the page's header.
That means its title, _Installing and Testing Silver Leaf's Prerequisites_, will be automatically assigned to `reftext` at runtime and used in <<ex-page>> as the xref's link text.

If you don't want a page's title to be used as its default `reftext`, assign the attribute a custom value with an attribute entry.
<<ex-custom-reftext>> shows the `reftext` attribute being assigned a custom value.

[#ex-custom-reftext]
.Assign a custom reftext value
[source]
----
= Installing and Testing Silver Leaf's Prerequisites
:reftext: Install Silver Leaf's Prerequisites

Here are the prerequisites:
----

When the site is generated, the value of `reftext`, _Install Silver Leaf's Prerequisites_, will be used in <<ex-page>> as the xref's link text.
It will also be used as the page's `navtitle` value.

CAUTION: When the target page ID includes a xref:page-id.adoc#id-fragment[fragment], the link text isn't automatically populated.
You'll need to specify the xref's link text in such cases.

[#navtitle]
== navtitle attribute

A target page's `navtitle` value is used as the link text in an xref that originates from a xref:navigation:files-and-lists.adoc[navigation file].
By default, Antora assigns the value of a page's `reftext` attribute to `navtitle`.
A <<reftext,page's reftext>> is often automatically assigned the page's title.

In <<ex-nav>>, let's reference the [.path]_get-started.adoc_ file from a navigation file, and leave the link text field empty.

[#ex-nav]
.nav.adoc
[source]
----
* xref:index.adoc[]
* xref:get-started.adoc[]
----

Now, let's look at the header of the [.path]_get-started.adoc_ file in <<ex-default-navtitle>>.

[#ex-default-navtitle]
.get-started.adoc
[source]
----
= Get Started with Silver Leaf

Let's get started!
----

Notice that neither `reftext` nor `navtitle` are set in it's header.
That means the page's title, _Get Started with Silver Leaf_, will be automatically assigned to `reftext`, and therefore, to `navtitle`, and used to populate the xref link text in the navigation file.

If you don't want a page's default or custom `reftext` value to be assigned as the default `navtitle`, assign the attribute a custom value with an attribute entry.
<<ex-custom-navtitle>> shows the `navtitle` attribute being assigned a custom value.

[#ex-custom-navtitle]
.Assign a custom navtitle value
[source]
----
= Get Started with Silver Leaf
:navtitle: Getting Started

Let's get started!
----

When the site is generated, the value of `navtitle`, _Getting Started_, will populate the xref link text in the navigation file.

CAUTION: When the target includes a xref:page-id.adoc#id-fragment[fragment] (aka a deep link) like `\xref:page.adoc#fragment[...]`, the link text (`...`) isn't automatically populated.
You'll need to specify the xref's link text in this case.
