= Xref Pages in Other Components and Versions

Sometimes you'll need to create cross references between pages that belong to different docs components.
In these cases, you'll often construct a fully qualified page ID.
You can also create xrefs between pages that belong to different versions of the same component.

[#xref-page-in-different-docs-component]
== Xref pages from other docs components

When the xref:page-id.adoc#current-page[current] and xref:page-id.adoc#target-page[target] pages belong to different docs components, you must, at a minimum, specify the target xref:page-id.adoc#id-coordinates[component, module, and page coordinates].
You'll almost always specify the target version coordinate, too.

[#ex-component-version-base]
.current-page.adoc
[source]
----
xref:version@component:module:target-page-filename.adoc[link text]
----

For context, let's use the pages that belong to the component versions `colorado 5.2` and `wyoming 1.0` as the basis for the examples on this section.
Their source files are stored in the xref:ROOT:standard-directories.adoc[standard directory trees] listed in <<ex-co-and-wy>>.

[#ex-co-and-wy]
.Standard directories assigned to the component versions colorado 5.2 and wyoming 1.0
----
📒 repository
  📄 antora.yml <1> 
  📂 modules
    📂 get-started
      📂 pages
        📄 tour.adoc
    📂 la-garita
      📂 pages
        📄 cochetopa-pass.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc

📒 repository
  📂 docs
    📄 antora.yml <2>
    📂 modules
      📂 sierra-madre
        📂 pages
          📄 elevation.adoc
          📄 wilderness-areas.adoc
----
<1> Declares files that belong to the colorado 5.2 component version
<2> Declares files that belong to the wyoming 1.0 component version

<<ex-across-components>> shows an xref in the page [.path]_index.adoc_ (current page) that links to the [.path]_elevation.adoc_ page (target page).
[.path]_index.adoc_ belongs to version `5.2` of the component `colorado`.
[.path]_elevation.adoc_ belongs to version `1.0` of the component `wyoming`.

[#ex-across-components]
.index.adoc (current page)
[source]
----
See xref:1.0@wyoming:sierra-madre:elevation.adoc[How are peaks measured]?
----

When the xref in <<ex-across-components>> is converted, it will become a link to the published site page at [.path]_\https://base-url.com/wyoming/1.0/sierra-madre/elevation.html_.

In <<ex-across-components-short-root>>, the page [.path]_ranges.adoc_ is referenced from the page [.path]_elevation.adoc_ (current page).
The target page, [.path]_ranges.adoc_, belongs to the `ROOT` module of the `colorado` component.

[#ex-across-components-short-root]
.elevation.adoc (current page)
[source]
----
xref:5.2@colorado::ranges.adoc[List of ranges by height]
----

Notice in <<ex-across-components-short-root>> that the module name `ROOT` seems to be missing from the page ID.
When a component coordinate is specified in a page ID, and the target page belongs to the `ROOT` module, the module coordinate `ROOT` doesn't have to be explicitly specified.
But you must still enter the colon `:` that would follow the module coordinate.
You can see this `:` directly before the page coordinate `ranges.adoc`.
This shorthand only works when a component coordinate is specified and the target module is `ROOT`.
In all other cases where the target module coordinate is required, the name of the module must be specified.

[#xref-latest-version-of-component-version-page]
=== Xref the latest version of a page

TIP: This behavior only applies when the target and current pages belong to different docs components!

If a version isn't specified in the target page ID, *and the target and current pages belong to a different docs components*, Antora will use the xref:ROOT:how-component-versions-are-sorted.adoc#latest-version[latest version] of the target component to complete the page ID.

Using the component versions previously described in <<ex-co-and-wy>>, let's create an xref in the page [.path]_index.adoc_ (current page) that links to the [.path]_elevation.adoc_ page (target page).
The xref is shown below in <<ex-across-components-latest>>.
[.path]_index.adoc_ belongs to version `5.2` of the component `colorado`.
[.path]_elevation.adoc_ belongs to version `1.0` of the component `wyoming`.
Notice that the target page's version coordinate isn't specified.

[#ex-across-components-latest]
.index.adoc (current page)
[source]
----
See xref:wyoming:sierra-madre:elevation.adoc[How are peaks measured]?
----

Since there isn't a version coordinate in <<ex-across-components-latest>>, Antora will automatically complete the page ID at runtime using the latest version -- `1.0` -- of the `wyoming` component.
When you release a newer version of `wyoming`, such as version `1.5`, and add it to your site, the xref in <<ex-across-components-latest>> will automatically link to the [.path]_elevation.adoc_ page in version `1.5` of `wyoming`.

WARNING: This behavior of linking to the latest version only applies when the version coordinate is unspecified and the target and current pages belong to different components.
If you don't specify a version and a component in the page ID, Antora assumes the target page's version and component are the same as the current page's version and component coordinates.

[#xref-page-in-different-version]
== Xref pages from other versions

When the current and target pages belong to the same docs component, but the target page belongs to a different version of that component, you'll specify the target version, module (if it's different), and page coordinates.

[#ex-version-module-base]
.current-page.adoc
[source]
----
xref:version@module:target-page-filename.adoc[link text]
----

If the target and current pages belong to the same module, too, then you only need to specify the target version and page coordinates.

[#ex-version-base]
.current-page.adoc
[source]
----
xref:version@target-page-filename.adoc[link text]
----

For context, let's use the pages that belong to the component versions `colorado 5.2` and `colorado 6.0` as the basis for the example in this section.
Their source files are stored in the xref:ROOT:standard-directories.adoc[standard directory trees] listed in <<ex-co-versions>>.

[#ex-co-versions]
.Standard directories assigned to the component versions colorado 5.2 and colorado 6.0
----
📒 repository | branch name v5.2.x
  📄 antora.yml <- Declares files belong to colorado 5.2
  📂 modules
    📂 get-started
      📂 pages
        📄 tour.adoc
    📂 la-garita
      📂 pages
        📄 cochetopa-pass.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc

📒 repository | branch name v6.0.x
  📄 antora.yml <- Declares files belong to colorado 6.0
  📂 modules
    📂 la-garita
      📂 pages
        📄 cochetopa-pass.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc
----

Notice that the `colorado 5.2` component version has a [.path]_tour.adoc_ page that belongs to the `get-started` module.
However, `colorado 6.0` has no such module or page.

Let's reference the page [.path]_tour.adoc_ (target page), which belongs to `colorado 5.2`, from the page [.path]_cochetopa-pass.adoc_ (current page), which belongs to the `colorado 6.0` component version.
In <<ex-across-versions>>, the xref specifies the target page's version, module, and page coordinates.

[#ex-across-versions]
.cochetopa-pass.adoc (current page) in colorado 6.0
[source]
----
Last year's xref:5.2@get-started:tour.adoc[excursions] were riveting!
----

When the xref in <<ex-across-versions>> is converted by Antora, it will become a link to the published site page at [.path]_\https://base-url.com/colorado/5.2/get-started/tour.html_.
